version: "3.9"
services:
  here-pysdk:
    image: here-pysdk # provide image name
    container_name: here-pysdk
    build: .
    ports:
      - "8888:8888" # ports should be double quoted
    volumes:
    # ex. \\wsl$$\Ubuntu\home\data:/home/data
      - \\wsl$$\Ubuntu\home\hnaka\share_w_docker\python:/home/share_w_host